services:
  postgres:
    image: postgres:18-alpine
    container_name: bank_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bank_card}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-bank_card}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bank_network

volumes:
  postgres_data:
    name: bank_card

networks:
  bank_network:
    driver: bridge