server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:qV3nL9pR2sT7wX1yZ5aB8cD0eF3gH6jK}
    expiration-ms: 3600000
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY:9fMovLiS2BDudjdOQ39LMotcTBQyLJ1UYwiDe53Glsa}

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:bank_card}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
